### PR TITLE
Update CITATIONS.md

### PR DESCRIPTION
**Pull request by sbooeshaghi**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/fetchfastq/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/fetchfastq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by drpatelh** [comment]
Hi @sbooeshaghi ! Thank you for your PR. I suspect there is a misunderstanding here because we have had plans to have such a workflow on nf-core for quite a long time now. In fact, this is exactly why I added such a workflow to [nf-core/rnaseq](https://github.com/nf-core/rnaseq/blob/master/workflows/sra_download.nf) and [nf-core/viralrecon](https://github.com/nf-core/viralrecon/blob/master/workflows/sra_download.nf) for it to be used and hence developed before we implement a stand-alone workflow. The actual motivation for me to add this workflow was because it didn't make sense to fix and update both of these workflows independently anymore and [this issue](https://github.com/nf-core/rnaseq/issues/646) was the icing on the cake!

The scripts I wrote for this pipeline were laid down over a year ago as you can see [here](https://github.com/nf-core/viralrecon/commit/2d5cdb3d8234e7f11c079fe57d8b131010423aae#diff-65121a65588bdb1c8d90acf0bdb50940c54c74a189e3e44ba2e91e5cdca9558f) and have since been improved and in fact pre-date `ffq` too as a simpler mechanism to fetch metadata from public databases.

Having said that, I would very much like to include the citation for `ffq` in an official capacity if we are able to integrate it as an upstream processing step in the pipeline. This is why I asked whether you had plans to add it to Conda in my [Tweet](https://twitter.com/aka_hpatel/status/1396951093087817734?s=20) because it would mean we get Docker/Singularity Biocontainers for free that we could use within this pipeline.

**Comment by drpatelh** [comment]
I have also just realised that the expansion of `ffq` is the same name as this workflow 🤦🏽 I would like to clarify that the name we chose was quite innocently the same as yours and we definitely wouldn't have used it if it was likely to cause any issues. We had a long drawn out conversation on nf-core Slack in a completely open fashion between numerous members of the community where we voted for a name to use. Given that I was hoping to use `ffq` in this pipeline anyway hopefully this is acceptable for you.

**Comment by sbooeshaghi** [comment]
Thanks for the reply but now I'm confused. [According to you](https://twitter.com/gau/status/1400545958073614339?s=20) `fetchfastq` was built "from scratch to release in a single day", June 3, 2021.

**Comment by drpatelh** [comment]
Why does that matter? We will find another name for this pipeline to avoid any controversy. I will try and find time to do this next week.

**Comment by ewels** [comment]
> Thanks for the reply but now I'm confused. [According to you](https://twitter.com/gau/status/1400545958073614339?s=20) `fetchfastq` was built "from scratch to release in a single day", June 3, 2021.

To clarify @sbooeshaghi - the pipeline repository was created and released in a day. The code was almost entirely copied from other existing pipelines where it had existed as a subworkflow. This is how the code has been under development for a long time whilst the _pipeline_ was built in a day. 

The back story is that the subworkflow was part of the rnaseq pipeline for a few years now. But several other @nf-core pipelines needed the same subworkflow. Instead of duplicating the code we thought it was better to move it into its own pipeline.

The naming and timing conflict with your tool was an unfortunate coincidence. You can see the discussion and poll about names in our (public) Slack [here](https://nfcore.slack.com/archives/CE6SDEDAA/p1622708056033400). You can see the discussion about splitting it into its own pipeline back in April [here](https://nfcore.slack.com/archives/CJRH30T6V/p1619688077164200).

We totally agree that the name clash could be confusing. We're currently [discussing alternatives](https://nfcore.slack.com/archives/C024915L4KB/p1622878889082900) and will rename the pipeline as soon as we have reached consensus. I hope this is ok - we should have checked for whether the name was taken first, that's our fault. We'll try to remember to do this in the future.

**Comment by ewels** [comment]
To add a bit more explicit clarification: I'm pretty confident in saying that none of us had heard of your tool before @drpatelh saw your tweet and replied. There's no mention of `fetchfastq` or `ffq` in our Slack before the pipeline name discussion.

We definitely did take some inspiration from SRA-Explorer (which I wrote) and I knew of pysradb. Nextflow itself also has [built in support](https://www.nextflow.io/docs/latest/channel.html#fromsra) for doing something similar (which itself was inspired from discussion about SRA Explorer).

As @drpatelh says, your tool looks super nice though. If you're happy with us using it then I think we could do well to use it and drop some of our custom pipeline code. We will of course do our best to give full credit if/when that happens.

I hope this helps to clear things up and get us all on the same page. We certainly meant no disrespect. If you have any thoughts on how we can use `ffq` or otherwise improve the pipeline we'd love to hear them.

**Comment by drpatelh** [comment]
Sorry, I should have clarified too. The reason I suggested that it didn't matter is that the pipeline being released in a day was a semantics issue and not the actual one which (I think) is being raised here i.e. the pipeline name.

**Comment by ewels** [comment]
The pipeline has been renamed and the release recreated: https://twitter.com/nf_core/status/1402328796515209221

Let us know if there's anything else you'd like us follow up on 👍🏻

**Pull request closed without merging**
